// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessageProto.proto

package com.hyc.chatproxy.tcp.proto;

public final class ChatMessageProto {
  private ChatMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hyc.chatproxy.tcp.proto.MessageReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *请求命令
     * </pre>
     *
     * <code>string cmd = 1;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <pre>
     *请求命令
     * </pre>
     *
     * <code>string cmd = 1;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <pre>
     *请求体
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <pre>
     *请求体
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     * @return The body.
     */
    com.google.protobuf.Any getBody();
    /**
     * <pre>
     *请求体
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
  }
  /**
   * <pre>
   *请求消息
   * </pre>
   *
   * Protobuf type {@code com.hyc.chatproxy.tcp.proto.MessageReq}
   */
  public static final class MessageReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hyc.chatproxy.tcp.proto.MessageReq)
      MessageReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageReq.newBuilder() to construct.
    private MessageReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageReq() {
      cmd_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageReq();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hyc.chatproxy.tcp.proto.ChatMessageProto.internal_static_com_hyc_chatproxy_tcp_proto_MessageReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hyc.chatproxy.tcp.proto.ChatMessageProto.internal_static_com_hyc_chatproxy_tcp_proto_MessageReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq.class, com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq.Builder.class);
    }

    private int bitField0_;
    public static final int CMD_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cmd_ = "";
    /**
     * <pre>
     *请求命令
     * </pre>
     *
     * <code>string cmd = 1;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *请求命令
     * </pre>
     *
     * <code>string cmd = 1;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.Any body_;
    /**
     * <pre>
     *请求体
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *请求体
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.Any getBody() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }
    /**
     * <pre>
     *请求体
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cmd_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getBody());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cmd_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBody());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq)) {
        return super.equals(obj);
      }
      com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq other = (com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq) obj;

      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求消息
     * </pre>
     *
     * Protobuf type {@code com.hyc.chatproxy.tcp.proto.MessageReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hyc.chatproxy.tcp.proto.MessageReq)
        com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hyc.chatproxy.tcp.proto.ChatMessageProto.internal_static_com_hyc_chatproxy_tcp_proto_MessageReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hyc.chatproxy.tcp.proto.ChatMessageProto.internal_static_com_hyc_chatproxy_tcp_proto_MessageReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq.class, com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq.Builder.class);
      }

      // Construct using com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBodyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cmd_ = "";
        body_ = null;
        if (bodyBuilder_ != null) {
          bodyBuilder_.dispose();
          bodyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hyc.chatproxy.tcp.proto.ChatMessageProto.internal_static_com_hyc_chatproxy_tcp_proto_MessageReq_descriptor;
      }

      @java.lang.Override
      public com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq getDefaultInstanceForType() {
        return com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq build() {
        com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq buildPartial() {
        com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq result = new com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmd_ = cmd_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.body_ = bodyBuilder_ == null
              ? body_
              : bodyBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq) {
          return mergeFrom((com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq other) {
        if (other == com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq.getDefaultInstance()) return this;
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                cmd_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getBodyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object cmd_ = "";
      /**
       * <pre>
       *请求命令
       * </pre>
       *
       * <code>string cmd = 1;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求命令
       * </pre>
       *
       * <code>string cmd = 1;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求命令
       * </pre>
       *
       * <code>string cmd = 1;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cmd_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求命令
       * </pre>
       *
       * <code>string cmd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        cmd_ = getDefaultInstance().getCmd();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求命令
       * </pre>
       *
       * <code>string cmd = 1;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cmd_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any body_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
      /**
       * <pre>
       *请求体
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       * @return Whether the body field is set.
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *请求体
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       * @return The body.
       */
      public com.google.protobuf.Any getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *请求体
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
        } else {
          bodyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求体
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder setBody(
          com.google.protobuf.Any.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求体
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder mergeBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            body_ != null &&
            body_ != com.google.protobuf.Any.getDefaultInstance()) {
            getBodyBuilder().mergeFrom(value);
          } else {
            body_ = value;
          }
        } else {
          bodyBuilder_.mergeFrom(value);
        }
        if (body_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       *请求体
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = null;
        if (bodyBuilder_ != null) {
          bodyBuilder_.dispose();
          bodyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求体
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public com.google.protobuf.Any.Builder getBodyBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *请求体
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : body_;
        }
      }
      /**
       * <pre>
       *请求体
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hyc.chatproxy.tcp.proto.MessageReq)
    }

    // @@protoc_insertion_point(class_scope:com.hyc.chatproxy.tcp.proto.MessageReq)
    private static final com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq();
    }

    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageReq>
        PARSER = new com.google.protobuf.AbstractParser<MessageReq>() {
      @java.lang.Override
      public MessageReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hyc.chatproxy.tcp.proto.MessageResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *请求命令
     * </pre>
     *
     * <code>string cmd = 1;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <pre>
     *请求命令
     * </pre>
     *
     * <code>string cmd = 1;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <pre>
     *返回吗，0表示成功，其他表示失败
     * </pre>
     *
     * <code>int32 code = 2;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     *错误信息
     * </pre>
     *
     * <code>string erroMsg = 3;</code>
     * @return The erroMsg.
     */
    java.lang.String getErroMsg();
    /**
     * <pre>
     *错误信息
     * </pre>
     *
     * <code>string erroMsg = 3;</code>
     * @return The bytes for erroMsg.
     */
    com.google.protobuf.ByteString
        getErroMsgBytes();

    /**
     * <pre>
     *返回体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 4;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <pre>
     *返回体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 4;</code>
     * @return The data.
     */
    com.google.protobuf.Any getData();
    /**
     * <pre>
     *返回体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getDataOrBuilder();
  }
  /**
   * <pre>
   *返回消息
   * </pre>
   *
   * Protobuf type {@code com.hyc.chatproxy.tcp.proto.MessageResp}
   */
  public static final class MessageResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hyc.chatproxy.tcp.proto.MessageResp)
      MessageRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageResp.newBuilder() to construct.
    private MessageResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageResp() {
      cmd_ = "";
      erroMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageResp();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hyc.chatproxy.tcp.proto.ChatMessageProto.internal_static_com_hyc_chatproxy_tcp_proto_MessageResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hyc.chatproxy.tcp.proto.ChatMessageProto.internal_static_com_hyc_chatproxy_tcp_proto_MessageResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp.class, com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp.Builder.class);
    }

    private int bitField0_;
    public static final int CMD_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cmd_ = "";
    /**
     * <pre>
     *请求命令
     * </pre>
     *
     * <code>string cmd = 1;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *请求命令
     * </pre>
     *
     * <code>string cmd = 1;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_ = 0;
    /**
     * <pre>
     *返回吗，0表示成功，其他表示失败
     * </pre>
     *
     * <code>int32 code = 2;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int ERROMSG_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object erroMsg_ = "";
    /**
     * <pre>
     *错误信息
     * </pre>
     *
     * <code>string erroMsg = 3;</code>
     * @return The erroMsg.
     */
    @java.lang.Override
    public java.lang.String getErroMsg() {
      java.lang.Object ref = erroMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        erroMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *错误信息
     * </pre>
     *
     * <code>string erroMsg = 3;</code>
     * @return The bytes for erroMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErroMsgBytes() {
      java.lang.Object ref = erroMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        erroMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.Any data_;
    /**
     * <pre>
     *返回体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 4;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *返回体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.Any getData() {
      return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
    }
    /**
     * <pre>
     *返回体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
      return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cmd_);
      }
      if (code_ != 0) {
        output.writeInt32(2, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(erroMsg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, erroMsg_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getData());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cmd_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(erroMsg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, erroMsg_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp)) {
        return super.equals(obj);
      }
      com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp other = (com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp) obj;

      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getErroMsg()
          .equals(other.getErroMsg())) return false;
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + ERROMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErroMsg().hashCode();
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *返回消息
     * </pre>
     *
     * Protobuf type {@code com.hyc.chatproxy.tcp.proto.MessageResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hyc.chatproxy.tcp.proto.MessageResp)
        com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hyc.chatproxy.tcp.proto.ChatMessageProto.internal_static_com_hyc_chatproxy_tcp_proto_MessageResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hyc.chatproxy.tcp.proto.ChatMessageProto.internal_static_com_hyc_chatproxy_tcp_proto_MessageResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp.class, com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp.Builder.class);
      }

      // Construct using com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cmd_ = "";
        code_ = 0;
        erroMsg_ = "";
        data_ = null;
        if (dataBuilder_ != null) {
          dataBuilder_.dispose();
          dataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hyc.chatproxy.tcp.proto.ChatMessageProto.internal_static_com_hyc_chatproxy_tcp_proto_MessageResp_descriptor;
      }

      @java.lang.Override
      public com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp getDefaultInstanceForType() {
        return com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp build() {
        com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp buildPartial() {
        com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp result = new com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmd_ = cmd_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.erroMsg_ = erroMsg_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.data_ = dataBuilder_ == null
              ? data_
              : dataBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp) {
          return mergeFrom((com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp other) {
        if (other == com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp.getDefaultInstance()) return this;
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getErroMsg().isEmpty()) {
          erroMsg_ = other.erroMsg_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                cmd_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                code_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                erroMsg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getDataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object cmd_ = "";
      /**
       * <pre>
       *请求命令
       * </pre>
       *
       * <code>string cmd = 1;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求命令
       * </pre>
       *
       * <code>string cmd = 1;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求命令
       * </pre>
       *
       * <code>string cmd = 1;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cmd_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求命令
       * </pre>
       *
       * <code>string cmd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        cmd_ = getDefaultInstance().getCmd();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求命令
       * </pre>
       *
       * <code>string cmd = 1;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cmd_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       *返回吗，0表示成功，其他表示失败
       * </pre>
       *
       * <code>int32 code = 2;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *返回吗，0表示成功，其他表示失败
       * </pre>
       *
       * <code>int32 code = 2;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回吗，0表示成功，其他表示失败
       * </pre>
       *
       * <code>int32 code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object erroMsg_ = "";
      /**
       * <pre>
       *错误信息
       * </pre>
       *
       * <code>string erroMsg = 3;</code>
       * @return The erroMsg.
       */
      public java.lang.String getErroMsg() {
        java.lang.Object ref = erroMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          erroMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *错误信息
       * </pre>
       *
       * <code>string erroMsg = 3;</code>
       * @return The bytes for erroMsg.
       */
      public com.google.protobuf.ByteString
          getErroMsgBytes() {
        java.lang.Object ref = erroMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          erroMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *错误信息
       * </pre>
       *
       * <code>string erroMsg = 3;</code>
       * @param value The erroMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErroMsg(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        erroMsg_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息
       * </pre>
       *
       * <code>string erroMsg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearErroMsg() {
        erroMsg_ = getDefaultInstance().getErroMsg();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息
       * </pre>
       *
       * <code>string erroMsg = 3;</code>
       * @param value The bytes for erroMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErroMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        erroMsg_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;
      /**
       * <pre>
       *返回体
       * </pre>
       *
       * <code>.google.protobuf.Any data = 4;</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *返回体
       * </pre>
       *
       * <code>.google.protobuf.Any data = 4;</code>
       * @return The data.
       */
      public com.google.protobuf.Any getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *返回体
       * </pre>
       *
       * <code>.google.protobuf.Any data = 4;</code>
       */
      public Builder setData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
        } else {
          dataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回体
       * </pre>
       *
       * <code>.google.protobuf.Any data = 4;</code>
       */
      public Builder setData(
          com.google.protobuf.Any.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回体
       * </pre>
       *
       * <code>.google.protobuf.Any data = 4;</code>
       */
      public Builder mergeData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            data_ != null &&
            data_ != com.google.protobuf.Any.getDefaultInstance()) {
            getDataBuilder().mergeFrom(value);
          } else {
            data_ = value;
          }
        } else {
          dataBuilder_.mergeFrom(value);
        }
        if (data_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       *返回体
       * </pre>
       *
       * <code>.google.protobuf.Any data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = null;
        if (dataBuilder_ != null) {
          dataBuilder_.dispose();
          dataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回体
       * </pre>
       *
       * <code>.google.protobuf.Any data = 4;</code>
       */
      public com.google.protobuf.Any.Builder getDataBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *返回体
       * </pre>
       *
       * <code>.google.protobuf.Any data = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : data_;
        }
      }
      /**
       * <pre>
       *返回体
       * </pre>
       *
       * <code>.google.protobuf.Any data = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hyc.chatproxy.tcp.proto.MessageResp)
    }

    // @@protoc_insertion_point(class_scope:com.hyc.chatproxy.tcp.proto.MessageResp)
    private static final com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp();
    }

    public static com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageResp>
        PARSER = new com.google.protobuf.AbstractParser<MessageResp>() {
      @java.lang.Override
      public MessageResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hyc.chatproxy.tcp.proto.ChatMessageProto.MessageResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hyc_chatproxy_tcp_proto_MessageReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hyc_chatproxy_tcp_proto_MessageReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hyc_chatproxy_tcp_proto_MessageResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hyc_chatproxy_tcp_proto_MessageResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ChatMessageProto.proto\022\033com.hyc.chatpr" +
      "oxy.tcp.proto\032\031google/protobuf/any.proto" +
      "\"=\n\nMessageReq\022\013\n\003cmd\030\001 \001(\t\022\"\n\004body\030\002 \001(" +
      "\0132\024.google.protobuf.Any\"]\n\013MessageResp\022\013" +
      "\n\003cmd\030\001 \001(\t\022\014\n\004code\030\002 \001(\005\022\017\n\007erroMsg\030\003 \001" +
      "(\t\022\"\n\004data\030\004 \001(\0132\024.google.protobuf.AnyB\035" +
      "\n\033com.hyc.chatproxy.tcp.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_hyc_chatproxy_tcp_proto_MessageReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hyc_chatproxy_tcp_proto_MessageReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hyc_chatproxy_tcp_proto_MessageReq_descriptor,
        new java.lang.String[] { "Cmd", "Body", });
    internal_static_com_hyc_chatproxy_tcp_proto_MessageResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hyc_chatproxy_tcp_proto_MessageResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hyc_chatproxy_tcp_proto_MessageResp_descriptor,
        new java.lang.String[] { "Cmd", "Code", "ErroMsg", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
